### ISSUE TITLE
Proposed name change

### ISSUE THREAD

**Issue by t-d-k** [t-d-k/doxbox#11]
Some have objected to the name 'DoxBox' saying it doesn't evoke the idea of encryption software.
Other suggestions are 'libreCrypt' or 'libreLocker'.
I have created a survey to find what name people prefer.
Please click [here](https://www.surveymonkey.com/s/2PC8C96) and take the survey, or add any comments below.

**Comment by conorkickass** [comment]
Great idea. DoxBox also kept getting autocorrected to DosBox when I tried to Google the project!

**Comment by t-d-k** [comment]
So thanks for a quick responses on the survey, the results are clear, people either love or hate the name DoxBox - only 4 people put it second. Although there were many 2nd place responses for libreCrypt only 1 put it last, so it seems a safer choice.
 The name will change to libreCrypt after the next release, and librecrypt.eu will point to the GitHub summary page.
The results are now public.
