### ISSUE TITLE
/dismount disk doesn't work on Windows 8.1?

### ISSUE THREAD

**Issue by bberanbender** [t-d-k/doxbox#14]
Hello, I installed DoxBox on Windows 8.1 and it works fine. However, when I try use command line commands, I've figured out, that /dismount disk_letter doesn't work. But /dismont all works perfectly.
Does someone faced with this problem?
P.S. Sorry, if I have any mistakes in description, I'm not very good in English

**Comment by t-d-k** [comment]
Thanks for reporting this. I can confirm this is a bug and it has been fixed. The fix will be in the next release.

**Comment by bberanbender** [comment]
And when the next release will be?

**Comment by t-d-k** [comment]
Soon
