### ISSUE TITLE
Can't see option to mount Linux partition

### ISSUE THREAD

**Issue by orion1024** [t-d-k/doxbox#5]
Hello,

from the docs it seems we should be able to mount LUKS partitions : 

Extract from https://github.com/t-d-k/doxbox/blob/master/docs/Linux_volumes.md

>Mounting Volumes Created under Linux

>Select "File | Linux volume | Mount file.../Mount partition".

But  I dont see the "Mount partition" option in the menu, only "Mount file..." and "Mount file (hidden)..."

Other info on my environment :

- DoxBox 6.0 Beta
- Windows 7 64 bits

Am I missing something ?

**Comment by t-d-k** [comment]
This option is only available in the main DoxBox program, not DoxBoxExplorer. 
This is because administrator permissions are needed to access the raw partition, and Explorer is intended to be run without these permissions.
