### ISSUE TITLE
[Feature] Support for EcryptFS

### ISSUE THREAD

**Issue by Redsandro** [t-d-k/doxbox#8]
Support for EcryptFS, a popular file-based in stead of disk-based encryption method popularized by Ubuntu and children, would add popular possibilities such as encrypting part of a memory stick without sparse files or dedicated partitions, or having documents encrypted on cloud services such as Dropbox in a Linux compatible manner.

**Comment by t-d-k** [comment]
Filesystem level encryption like eCryptFS only uses up as much space as there is encrypted. 
As you say, this has some advantages, but also means an attacker can tell how much you have encrypted. This makes it incompatible with Deniable Encryption.
 It would also be a lot of work to implement a new encryption scheme so this will not be done.

**Comment by Redsandro** [comment]
I understand. This is not deniable encryption, but it is unstealable encryption (family/hackers/competitors).

It would be a popular feature because there is no EcryptFS software available under Windows, and it is superior to the EncFS that BoxCryptor and the likes use. It seemed like a good idea to at least put it out there. Maybe if a highly motivated developer googles and ends up here, things could happen.

Just since every encryption software (on Windows) seems either poor or proprietary, and after the fall of FreeOTFE and TrueCrypt, it would be fun to eventually have a single tool to rule them all.
